-- 휴지통 테이블 (삭제 되돌리기용)
-- Supabase 대시보드 > SQL Editor 에서 한 번만 실행하면 됩니다.
-- 삭제할 때 지워지는 행(연쇄로 함께 지워지는 지원자·수강생 등 포함)을 payload에 그대로 보관하고,
-- 휴지통 화면의 [복원]이 같은 id로 다시 넣습니다.

create table if not exists public.deleted_items (
  id          bigint generated by default as identity primary key,
  kind        text        not null,              -- '공고', '학생', '지원자' 등
  label       text        not null default '',   -- 화면에 보일 이름
  payload     jsonb       not null default '[]', -- [{ "table": "...", "rows": [ ... ] }, ...]
  deleted_by  text        not null default '',   -- master / staff / staff2
  deleted_at  timestamptz not null default now()
);

create index if not exists deleted_items_deleted_at_idx on public.deleted_items (deleted_at desc);

-- 기존 테이블들과 같은 방식(anon 키)으로 앱에서 읽고 쓸 수 있게 합니다.
alter table public.deleted_items enable row level security;
drop policy if exists "deleted_items_all" on public.deleted_items;
create policy "deleted_items_all" on public.deleted_items for all to anon, authenticated using (true) with check (true);
